/**
 * MongoDB Schema Documentation for AI Interviewer
 * 
 * This file documents the database schema for reference.
 * MongoDB is schemaless, but this shows the expected structure.
 * 
 * Database: interviews
 * Collections: interviews, transcripts, agent_state
 */

// ─────────────────────────────────────────────────────────────────────────────
// Collection: interviews
// Purpose: Stores interview sessions (one document per interview)
// ─────────────────────────────────────────────────────────────────────────────

// Example Document:
{
  _id: ObjectId("..."),
  
  // Unique identifier (generated by UI)
  interview_id: "ca0a4375-41dc-4eba-bd65-fe6c2c934943",  // UUID, unique
  
  // Interview status
  status: "in_progress",  // "in_progress" | "abandoned" | "completed"
  bot_status: "admitted", // "pending" | "admitted"
  
  // Candidate info
  candidate_name: "Ghulam Mustafa",
  candidate_email: "candidate@example.com",
  
  // Meeting details
  meeting_url: "https://meet.google.com/bks-ipsc-vak",
  
  // Job details
  job_description: "Software Engineer position...",
  company_info: "TechNova is a leading...",
  
  // CV/Resume (stored as text)
  cv_text: "Experience: 5 years at...",
  
  // Timestamps
  created_at: ISODate("2026-03-14T19:17:00Z"),
  started_at: ISODate("2026-03-14T19:18:00Z"),  // When bot joined
  ended_at: ISODate("2026-03-14T19:30:00Z"),    // When meeting ended
  
  // Bot health monitoring
  bot_heartbeat: ISODate("2026-03-14T19:29:30Z"),  // Updated every 30s
  
  // Interview metrics
  phase: "INTRO",       // "INTRO" | "EXPERIENCE" | "TECHNICAL" | "CLOSING"
  turn_count: 3,        // Number of Q&A turns
  duration_minutes: 12, // Total interview duration
  
  // Cleanup metadata (added by cleanup-service)
  abandon_reason: "bot_heartbeat_stale (2.5min ago)",  // Why marked abandoned
  abandon_duration_minutes: 15.3,  // How long it ran before cleanup
  
  // Indexes:
  // - {interview_id: 1} unique
  // - {status: 1}
  // - {bot_heartbeat: 1}
  // - {created_at: 1}
  // - {status: 1, bot_heartbeat: 1}
}


// ─────────────────────────────────────────────────────────────────────────────
// Collection: transcripts
// Purpose: Stores conversation turns (one document per speaker turn)
// ─────────────────────────────────────────────────────────────────────────────

// Example Document:
{
  _id: ObjectId("..."),
  
  // Links to interview
  interview_id: "ca0a4375-41dc-4eba-bd65-fe6c2c934943",
  
  // Speaker identification
  speaker: "candidate",  // "candidate" | "agent"
  
  // Transcript content
  text: "Hello, my name is Ghulam Mustafa. I'm from Lahore, Pakistan...",
  
  // Audio (if TTS generated audio)
  audio_url: "69b3d5184f2497fabae4e744",  // GridFS ID (null for candidate)
  
  // Timing
  timestamp: ISODate("2026-03-14T19:18:06Z"),
  
  // Metadata (for agent responses)
  phase: "INTRO",       // Interview phase when spoken
  turn_number: 1,       // Which turn in conversation
  
  // Indexes:
  // - {interview_id: 1, timestamp: 1}
}


// ─────────────────────────────────────────────────────────────────────────────
// Collection: agent_state
// Purpose: Stores Main-Agent state (resume token for change streams)
// ─────────────────────────────────────────────────────────────────────────────

// Example Document:
{
  _id: "resume_token",  // Fixed ID (singleton document)
  
  // MongoDB change stream resume token
  // Allows agent to resume from last event after restart
  token: {
    _data: "8265F2E..."
  },
  
  // Last processed timestamp (for debugging)
  last_processed: ISODate("2026-03-14T19:30:00Z")
}

// No indexes needed (single document by _id)


// ─────────────────────────────────────────────────────────────────────────────
// GridFS Buckets (for audio files)
// Purpose: Stores TTS audio files (binary data)
// ─────────────────────────────────────────────────────────────────────────────

// Collections (auto-created by MongoDB):
// - fs.files    (metadata)
// - fs.chunks   (binary data)

// Example File Document:
{
  _id: ObjectId("69b3d5184f2497fabae4e744"),
  filename: "transcript_69b3d5184f2497fabae4e744.wav",
  contentType: "audio/wav",
  length: 168000,  // File size in bytes
  uploadDate: ISODate("2026-03-14T19:19:08Z"),
  metadata: {
    interview_id: "ca0a4375-41dc-4eba-bd65-fe6c2c934943",
    transcript_id: ObjectId("...")
  }
}


// ─────────────────────────────────────────────────────────────────────────────
// Query Patterns (Optimized by Indexes)
// ─────────────────────────────────────────────────────────────────────────────

// 1. Find active interviews (for cleanup-service):
db.interviews.find({
  status: "in_progress",
  bot_heartbeat: { $lt: ISODate("2026-03-14T19:27:00Z") }  // 2 min ago
})
// Uses: {status: 1, bot_heartbeat: 1} compound index

// 2. Find interview by ID (for UI):
db.interviews.findOne({ interview_id: "ca0a4375-..." })
// Uses: {interview_id: 1} unique index

// 3. Get conversation for interview (for conversation view):
db.transcripts.find(
  { interview_id: "ca0a4375-..." },
  { speaker: 1, text: 1, timestamp: 1 }
).sort({ timestamp: 1 })
// Uses: {interview_id: 1, timestamp: 1} compound index

// 4. Find old interviews (for cleanup):
db.interviews.find({
  created_at: { $lt: ISODate("2026-03-14T17:30:00Z") }  // 2 hours ago
})
// Uses: {created_at: 1} index

// 5. Count interviews by status (for dashboard):
db.interviews.aggregate([
  { $group: { _id: "$status", count: { $sum: 1 } } }
])
// Uses: {status: 1} index


// ─────────────────────────────────────────────────────────────────────────────
// Data Retention Policy (Future)
// ─────────────────────────────────────────────────────────────────────────────

// Recommended retention:
// - Active interviews: Keep indefinitely
// - Completed interviews: Keep 90 days
// - Abandoned interviews: Keep 30 days
// - Audio files: Keep 7 days (re-generate if needed)

// Example cleanup query (run monthly):
// db.interviews.deleteMany({
//   status: "abandoned",
//   ended_at: { $lt: ISODate("2026-02-14T00:00:00Z") }
// })
